#!/bin/bash

echo "starting post commit..."

#Copy last commit hash to clipboard on commit
git log -1 --format=format:%h | pbcopy
echo "commit hash saved to the clipboard"

echo "...post commit done."

